apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:1eIZ8AfMdQP/7BUbUNCwRDv6siUlbmSg5b/5jp/iGt7F+92W,iv:HaQzVQPSO3iiH6LMsvLkBW8D5AZaHGUuaerveOxe7S4=,tag:/ogkOYesAYQz6/Bl2fpYpg==,type:str]
    credentials.json: ENC[AES256_GCM,data:mudfm1QZxepY3yLtT/LVqg8e7QLWg7OQG9CejIBuUXWAPYliBlyZS9xZm1Tti/qK/dtTxICLp4uUcLI1rY+1TfvOxBHD2zoD1/wdWP45eGZSGCJqa0TCZGKgc1DL3i+LJyHVvegI6cfSxlvsZCoBqRN3UN+oFH1Rj1sBNcgcNPz3WDlFO8qSUOhcSQ/ru8/3eNPWbIpLETlKO0rjcDEPfbQrVnIPOBW+K/Zp7jTLtQ==,iv:ashSfc0fKsnmCQBuxY0L9YB3O/2ixtWTvR8odEfKxfE=,tag:tDbjk7cWW0YTJhwGKEbzUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqWEtUams0NVhwYjFGb1Zk
            dVpsK0R2SjVwZndjaWYydVV4U1VxbFdPcVFnCjkrdXMzdStZSG8zOGE5UHNHd2Jq
            QzN0ejdxY2JNdmNEZW1ZNEh0VzVhWmMKLS0tIE5rbEYyL1dZMDVSa2JIaEJ0cHI1
            bWgrNTFCSE9rS3Z5NDk0ckQwVDc2QjAK7uG7xMkVRpUpxwY65/SCEQAgyD6sFMjs
            QlaxsN/e1jYrMnmDwQhgFp20g4tLQxfC/iaxwgLAr4ZtRWm6nyDEJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:39:17Z"
    mac: ENC[AES256_GCM,data:3D0TzqJx8dwiF9cXfyikvaf0wPeQUemPahcl4Odau0QUPSjUbv8WL1+dlx/wQClx+HY7Cu1UwlIT/OBuVKiw/sXyOOlhKKRH9R2fMzR/pO5zmego3ZQPnZHv3iPuOyghbjSpdNYhDQxYCdc+FsFmraBBYJ7SHWLTbdMh8EpBb4k=,iv:uOLc2i232MaC85PD4HmKSOnfyX8NeoTljg6IYZbNFXU=,tag:vSGTgUZIrFRV0DPFvHUEAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
