apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:HFynuwfkjwM=,iv:8bHxCK/y8fQX7YSaDWKxti2qV2Z7iomroyI+/vu0jm0=,tag:eRH5H6VgXdiGpFIyWfi5FA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:qYtIBacvJcy4cM6nI04=,iv:ovAe8q0d9qik1kc2x1BRso8+l9W+IUnJER0C8bZAs40=,tag:8laU78yts/IsFcc7cCKx9A==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:sgJC7wnbMSQSI2IA8lADuA+C1hDGQwcyJur58fYgtmZT4jfk,iv:IzvZcJKKrHZ8oS01KYDIYVIKH+/sECshiLUDMMrzYqY=,tag:MY3QVz33tUeB+59OXftM3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N2hWOUo2VWJNSWVmZGgv
            eVZkeW1OVEVjZEF5elN3bVdZZ2ZGRXhRUTBVCnNxbFdNMXI3Ky8wWHJXYVZCWC9O
            WWlIdklENk1RWkVrRjU3RmtkT3BtbGsKLS0tIFdVQnFsMzZxY2F6Y2pvcU41VUZ5
            MEJ4aDdMcjFPdmJFUDVCcEFPem1venMK/97XDHJn16aXUTktD+uzKvVRxtW07Wxw
            6olxTUuwH7j/Uh3whBi+vbCLTNlj5FHRWqUGkbzcFEbC7QCbdhuW2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T20:04:29Z"
    mac: ENC[AES256_GCM,data:1nflMz8ftOy9HRUQIhxJUady8YS6lAzDIoJaHfYvPAOg1C4bD65YwDM5zkk5jPZlk1n46XnF7HQ5Zo9QW+/kImxUguKOyJQFJj3oyg0UO8AEYKHgLWfWovKLUVtfWhQ3KgvCedy1y7V/TlX3XvhRjKOnzOaMAAtCpySYCrzDiE4=,iv:+E3JAALSy2OqExbUwLmbyaggUV99BO+ap2AwTGN2Ock=,tag:Fh+kkh/6/CZ/H6qAW0VdZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
