apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:y3ZVzlOo8Yk=,iv:9pV0k5GKYeNTHIua1BgRty7OWa1UTThIpkZVJ9gw9Zs=,tag:j9o+xTf6XvCtn/GngCs/NQ==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:0UsafQ2xPRtPXLnQfLY=,iv:K50inD2/GgopOkuGrVBbk23LgCxujVtxYzHOkiu5cfI=,tag:6PhM+Ep4aLUnO5SQOGoClQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Ya7fCTEEoll6IrTzx4bYuGDcD/C+XUy4m6OghI+ebXOtAfrK,iv:yfCzItGCoqu4BAB9sBvVGG0L6Vdr9+nehd8QmbIol1M=,tag:HlZRODQmNrYiTw6nKy1S6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSVRnY2U1Y0lESG0xZ21D
            VWhqUkkyZXVwbWFHb1E3MWhHZEZGZ1pMTUJvCjg3NDRZT3RYdDg1Q0RNSDdZOG9E
            UUJwenJtQXpqSEg0bGR0ZktVTUNOQTAKLS0tIDNjRUlGYnVZK0w5SDBwSFFzSy9k
            RmtIUnQraENYQkFSNmw0ZHZNS0crMmcKMEFkObhO/4Qpa/P+sBMtMrFVffEROJ59
            pnTzvk2HHofLFurO+/U3hkUBMwVWlLYs0GQ4v8KFmQotIAW9qYHcsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T21:27:46Z"
    mac: ENC[AES256_GCM,data:rR1Mu4NT2VnpGWWMijJCijQh6A9gRMYaRFH/kFoUCl6r2q00/QCqCem9KQannRNxiA2UktmNyhhfKTdg7H82AWjfn6PLS+AzPEApxFBvfUxwL3K13557vTmDypIo+pNnfd1K18CMnH/pzb15xf1DfML763xVKs4wCVexwfBXs7A=,iv:pWLG05d9Iaek30w84Gmqs+INaqbYl+x4q1qr1pab6wk=,tag:T+VGN3dxOsuYunzwn5yr1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
