apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:k8jxAaZb7Dc=,iv:MqjalK54pNqw7nScAT0h9HxDQ/XdeSS6lSR4BQqoHiw=,tag:rNczMb8HugEdPMVhaQ+Gdw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8DlzaCjk1gh5DDXxRK8=,iv:4LzUNOVVq6NPbmMkt5wd1g/PTJhUiqSGPaMAGOtLK9k=,tag:7b0B9x0Ks4KJUK3DDjgSfQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:UaT96LRpkrCH6KgEZsa2IvD62evmtmhSo1B+QM1UqIfKvKDi,iv:E8WK20+5ehQvKw5QMWbblXa1z6rDRtLb5moGksNVpM4=,tag:HNtkkckszzQpRXTQWRJHhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NmxmaU5xUWVtdlA2VVYy
            d1NMVy95OWdBZzhaMjhIN0JTOGVYNVNyQWp3CjVhb1c1dXN2N3p6YlFXSnVtYWpN
            ZFNrQS91UUJEcVlYZFdxSnMxZUh0Q3cKLS0tIE5sa2ZURFo3OHdCU0h5WE9DQUcr
            alQ3b0JSY1Jnd3krUUhGL1BmMTN5YUEKwxVHwqHeU6ENTkYXh1QHA0DFuIK45wk2
            ZWBRlly/kDVKof78wG1v8/Wh77Ul2DZQrQrkleLqSOJmfGFeJ89MHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T19:21:20Z"
    mac: ENC[AES256_GCM,data:G/p+e7v/6B8YD68JOEuJT7dqO3JBDMACIjsMaBBUDpkkS1hwK2axB6kBFO9/gkRnwFbbQj4HR+HhiAn5UbJS/gy+AouoZeU+zehvgxuBQtr1bTwveLz25BJhggwXzfOiGYirFwX2b7hcj0ISAh0LNIIBEjXBqmpCFVEqRVDl/I4=,iv:IqyXhSlYT0KKd+1s+s6NotdKvPkYxJHs2okdIO+rjFk=,tag:G8nQyA+I9ksfb7w+plSItw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
