apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:GDxhBF//XxQ=,iv:EqCG5dhj9UESBTdxQkD7qXuNHUdOsI2ov253bGGcY6M=,tag:mhmuWZpLvWjFAhP/6jh5AA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:sVD0Zn+SjyeamUEG/6Y=,iv:jgkAG7qObx/YFELVfx1ha+6xnt0uE72Y+5bvZnpmbr0=,tag:U1rYsFqncN5/esIgusz6HQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:7Ip2LTXQD3+1pqG4afCJrqWvRJLx6L0+Uc/W5Np2txjQ7PYC,iv:vs2ky+V5FS/Cx2Nz20Tqny5a30w3SmJcbLOk8idoafk=,tag:/3YmM/Vt+FdjjyNZfUNmbg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YnZYcjlsL1dGNlUxLzh3
            US9TL2s2MnZlQm1SQXJOU2UybzVtbkNrMXg0CndnRnVMOEtoTzdlZGFlbXBCR0wr
            YXFkeGZqbDl1RkZkdjJhclhDWnpkeDgKLS0tIElhc1Y1cTlSVW5HWlV0QnN2UjBP
            cDVDd2NtWHN2dnBmdGtHUW0zTDZ4TEUKb/sJesKUWkOy9KP/T3Z9KJDCs5GJ7rpC
            QfHv38uok/Qc6j9685k1Zaqugx+W6YYdOnaNfUOa4yXeXWSqs5hJ9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T22:39:17Z"
    mac: ENC[AES256_GCM,data:UkCDAE9V4+mo8zwCzgo5fGFQfrXi1wV3D92ggstPEXlktw85cMrbjncTCs2FezfcEAlWUjz5MQaByh166gusDP9kXgywwYZkW6rYP7SqTMqF6lq5Ras9xxojCRQOWq7rJkhUv09sfSMZVLgV2R/KIsHe5dyQeMt3HpUYCLGzAX0=,iv:7SJXOc/CLuMjMJxnINnGLcPIY+57eg8i5Y7NNatiuIk=,tag:0t1nEheeCo5pXyky6lvcyw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
