apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:7KcS3Qqv3tw=,iv:kFK7NI5sW10wE92P0/LfhkC9rjRSaE21ttQx4J83j5o=,tag:ub3ORPivxKORFP3dd+KtHA==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:qDsqE+EK2sACTgE7oy8=,iv:Opm3PKDa9XDqVevzvfY504WbrdBR/dIqXOsQwq2PQ+M=,tag:UGvrsS8FCLPz31db52b0hQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:HA7RlumUsQnSR7UsGzBBpprsR44eh6yL7N1ihmTIDGvB5Nh+,iv:cmkUJ9TyLB1UlasEFNuaIewlg+g9PG5P86PfAcu3ZDQ=,tag:IM3tNuWbxTDSs66xK5kdHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzRHNIWFJwYkM0KzFrdklo
            SzFNc2RqU212dU5mR2FUSHhhMFArVWdFNnpJCk5kTnBRSWpqT0drS3gySVJTUVly
            cTA2UThjS3JxN21aSkt5cm10ZnFLYncKLS0tIFc5dm42YXRoN1oxR2Q5OFRhdXN2
            b1c5cVBNdnhGOVVZdHYwOFRueWlqbEUKvCdm83lyvdLntYybFnbVb+4F9jG0yl4w
            LngASwsxjg/WDMQQ/oM88R1RpFs8cYINiw1g+yeIH2MUPfu2D+6WmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T22:53:38Z"
    mac: ENC[AES256_GCM,data:A87g6zwzdY/aXDLxLW8KAUQF5RPYCktLsVB9La8t5TWRAcDMg/4M4nhChNkPUdoNn92o8RoMzjMhSs6+3F/Gay8tJtdLDAkNylEaxuD4hpYVZmbTcmR1ld7sN1VvbGovkAp9o0pCgs3tPuOZGpdZqD8naQfbNipLQwbu9APoGQ4=,iv:bUVfZ65Pw7fGLV6FJrNarktVfD2UD44g3AfuuyhLMqs=,tag:JSilumB/T91pGp5PJAzLhQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
