apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:o8kZ,iv:gF3k7kW0xYe5LsEzCKrHgHndRVqVPNWJur8UABdqIkw=,tag:oAsMOdBDTP1osoXO8bOzUw==,type:str]
    password: ENC[AES256_GCM,data:Z0/pprwhkkGbxhE6bbSNKgOxPPUxZw==,iv:NHiLyRGYXbJysMQHbQQ7YGyB25KYHZvpNdaHqlsg3ZI=,tag:OFRHixYlv6AzyIbn++KIWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWGY3U2Q3Q2FpUThmNU5T
            Y1NmK09Iekkwd1Q1MWFGMlZVVXRwYzA3bFRBCmZselNVS3ptRExRSlNXdHZlYUUr
            M0FNVDE4L0VqZzFkT21Dc1N0MHlOWG8KLS0tIDMycUYxdlpVVi9ZMEFyTzQ1Ny9p
            cnFkMmVaSWYrZ21hamk5MFp2cm5Kc1kKyugKL7mJGgbHb1vDr1c/VOyQHuB6pwFp
            /wODSxojTOM2KUISI5NEl9Lzzxp+kVvGMxTred4i/5vhNp05xEWIIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T22:09:48Z"
    mac: ENC[AES256_GCM,data:OSMpzfV99FagTqd86hpVHhcgEVCORTSh0jdeWs4r88qeGnsWiWkkTFzEfqekY39uUe59JcB/TU8um0U7pje+zNJKSUuLYAjb8qHV6L7sRJEgmtPnMCL6lloW5yXKrQP1cPF5p7HTHwy0KrCyWgQ+0GdiZRck48P6RJI6ow0NcYo=,iv:ea6Ot3OyUHN9Dq3aQiBlocDGk09YHTea9NpdMEGmRm8=,tag:IYOK7mqMXq3jWeKaR9iLVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
