apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:UA8A,iv:eEc0iO+i/8CZhjC27Ur6Mb/pPSHfbS+EdFfYq3ma0Ko=,tag:Add0gJVeRcIIzEdviEVSLQ==,type:str]
    password: ENC[AES256_GCM,data:3QtpEqyRKLs+YhcJ0mClOF4FnifC4w==,iv:2+DgOVh94Xkd+mO2veTs4+lxLsHmsQ/JaI2rLfGbM6Y=,tag:X64hQ2z2rlY07GL8Ip88Fw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZFJKM3ZPdjVISXllQnY5
            UXRPQnhQSitoaCt6RHd3S01iUnh4TVR4TFRnCktjVXc4eCtWRlE4VXdGbm5tdUg3
            UGNWY1J0RHFsdnlPM0wzTmNya0hmdHMKLS0tIE5tY3BTbEczOVR1ZkVVY3AvakV2
            VjJabVJMNFE3MEFhcml4S0hqWGtVdmsKopPgVlw4fXIFgILIWMK5NRKfC/JxRHU3
            HdjboMDvAx4HfZQ21V9DZtzA4YnaQ1aRzJlmpW9rWvk+s8l4C+tMsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T23:02:57Z"
    mac: ENC[AES256_GCM,data:KoEad3nQvIz/n+oawvdWWjH9NpIoBg4FFPIYNqs3LCgCUt+PvfGmg1lyvNd4oHdefqny5kl+PgGL3foUellb2/eDD41p9ef8CT+SCKt9KT2JLBEnhhd2LaIQ8JfMDQq4EZGC+TBkVNfOUBJ2gmqM02jonslsCukNra+8GAVdSKM=,iv:h9YWkXLDJiNpvsCGcfinczeqCpzNcOnES1YNI6lJupE=,tag:G6/hym2M20IV63S7i5R5Eg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
