apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:TS6B,iv:I3NFQTVjHNf/Y73rmR/i6PtbukGPlmmnFGMh53IR05g=,tag:KYpD+ng79h5Ar3ZQsSieOA==,type:str]
    password: ENC[AES256_GCM,data:pq4URKT3GDJHFivBVaBDA7ygaKYs5g==,iv:JUyt3rnQy+a9eAfwTGwxoPM0GunNFz3GOhC9i7xeqe8=,tag:HJldNoLcDvAaYQTY+zQs4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQmdqTVIwbE12VEtWYm9k
            TEt3eGhoNjZzb3FFUU9XY0ZkQlkyZ3NCUUNNCkdiTE5TUmtCY1BvUGdGN0NnWnlX
            TzN0a1c3eXV5RExHT3liS1hOcTFOY0EKLS0tIFpQNExyZEkxMlJoUGhkamxBSGw0
            dEhxbU02ZytyYW50TGd2U0dUZFhoYUUKjVilyuesJIV0qKQQyx4UIyKdixQJr8aN
            aTa09D4J/yuq6QywURkM75SHWgaLV1KDmvQ+AluXDD5yEaELEEAZSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T22:53:38Z"
    mac: ENC[AES256_GCM,data:B9vxIkJHLqvAY2zSxIgH/YiIoWyeChLOmDDqNGy6WYP9TxMDxCfx57F8GCX4PUOi7AV6Q5fp4c1oDOC1hhCJMciV3blgXweHgU9pyNSPURYVaP0zGdCzc+xi6uR2Ss6Z4eBJP62LTfE5RT14o2Wv7roCzrMJQWNQ9lVh5Np1ImU=,iv:0mvTt1fXCmjcwXoaGzPzBto+6sxOrt6rBVTkjz5Ij70=,tag:bMbfAhcF3m3Qdpu5zTu61w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
