apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:v3riN2G7RXki5yRAIQEEUnSrkUdPzECE+ocN3UdFuhY=,iv:TZrje4gbL1YfdnwsBxcDHcMVdchcoON359CbdYjPdjY=,tag:tCI4WRjn+sQtdRkQYe/RaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRc0dwUkJIK0RIejBEcVhF
            VGVOeHhRSEw0S2dsNjhadkROZnZIa1Y5ZVdRClZEL2JOZWJwdFBVcjFnaklOTTRv
            ekgrSWh6R3ExWkZ0L2tGUWgyTjFZWlEKLS0tIFhhVkYyRmJhaENWeWJXV3N6R1RE
            dVhOUFRYTStJOGExUFc3YmQvQlJXZHcKDCGK+QTRaWLjblc0cuAF2g8iKze5h2zp
            Jp+J8vtebuwyWFRJ7U2Gkam6mx3NnTsaG/tNlKyVc7yoe28X0PibwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T19:21:20Z"
    mac: ENC[AES256_GCM,data:myRj/bssLUaeh0OIfAGUdhuvt8WJ/EgDOfuw1Rkp5wMjGUPZ82mcTYAFbRDxd9Bn88KrbkpdUcL5taJ6OQUPYXH5IdCqt9I8Oo51SBbDO8PMKeIpdSP6nQeMTsA7H76b4NnmrhF2Fqt9kem8g1rDb4k/rwcoqI+dyQcPP4IAPdk=,iv:gcgulSUVhNBWcaKy/2b1fh0ng8Cb2k/D0jRnDwX+qZg=,tag:dCb+Hi+1oZ8flNkx6JFpPg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
