apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:IpqlpzW35VUbA43buiRZalhI1DfamETroZW2Z6vpmYA=,iv:0CoDRIHvIlVInCyr+fNuDmSvIR+kilaLpr3jJHL1+L0=,tag:dgmMSo18deY4eSHAkM27Rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcVNLa2w2bGsyemlLKy9a
            VU95N0ZYa2hmajN0VnJLQ2VpeHB4d1dCMWpRCkM1LzVkTC8yMldDRkdnRlg1OVRx
            cmhWb1NZQ25XbE42Y2RFOUg1SS9ZLzgKLS0tIFBoWHViME9kTXBOS1pSZGhQZnJS
            V1NUcUUvWXd2ajRDaW56RnRRM1FJLzQKygUQNFkwQvJL6Tj/F/Om3gPV39n/rRl2
            hSUDyC+a02ezOdYZjSbwl2xrOcCDPUmY0EDNQleVqq2kkKs+/drEhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T22:09:48Z"
    mac: ENC[AES256_GCM,data:T5cIeW7C9a2A+o6aM0Mk5/PmHfHximmv5AG760fumoQ/RzX7jeejEiZQRbvkhRn6B9xUkgYuBhE01MV0ZqDoXXLD2Xu+ObmkOvsCkTSFlHJ2LiKUY4+cE46WOXGuZYg69ek9cHiQoIDpunwIuo/IXiOQfM72bHcVXRuu5BUFU2U=,iv:JFfxExSO1sAtOlvLUupvG90FTFhrsZSOlYbvW36ck6k=,tag:NCmMUh6en1EXMXBwPcjpWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
