apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:GWvmVcTSIxPkdYuj7YF/IfmUEenZWgsfLztqxYqdpDs=,iv:vKYWIJuKihRbhr0yurXgnz0MOYJ2fahEDs1YMGFz/JA=,tag:vcyTm6xJ6HywzMfui09QLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVmlCS2UwejFYaksrQVdt
            R0FrQVYzOFdOanB1YU9zeXB3TVVHZVZtSjJvCk5iTW44dW0yL0NZZmdVWFhia1A0
            aHgzTEIya095NVVkVVRJbE1EZ09ZU0UKLS0tIHY4R1ZKZ290QzhsSms2emQrUEFo
            SHJ0Z2N3TndLek1xZzgwR252NW1OSVEKMtluw7wkF7zErdXFxgUiY9EfvPeDfUzP
            /oRJKDaCPrctsQdY/c6KYkvdbiM3RLKNxJhpiE9kLuWthJXd7/INMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T21:20:15Z"
    mac: ENC[AES256_GCM,data:EG1RUdQi5JoldhknFX3p3uG4HXkfcUqPl/aRjjQBCUPhbWh88bYOSGYAR1PTqRmFb8Pr2dMf/tMgu6Dj/S+qRFWEU+gl2fwrTxGrX6hqHrlvUdGtMU5jJY53QDiLBzytSNZJCxWxYWYcmP3Cj1Yl6CBMeXDEFn9HczUiuB+Imc4=,iv:qHgt8MuyDtRIvsRjWFrS1ThuREhL/KDcw9KLEwWvQkA=,tag:R1ZKYip7ObI7ZxsftVGu5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
