apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Io/4CwTi3Knb3jDWXaksKs/9h6WDFNviOmiNyFmf1K0=,iv:nIfpQltpQuZUpTcCI7imQ/P2w/kPI7ZClBi6qeVu7J0=,tag:t9WW4V7jNJWfDpP32Xh9Kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4QlpJSkdyZ2xtSVd0NEFk
            cnNzaXN2NEJLUktjTEdxQnQxYkpyenBnY2lrClhiTW1xRWpXNFlrckJGQXJPTVZy
            SUlRbVJuNE9ZdTMwTGVxbzlOMWY1d1UKLS0tIDhiSjQvQlpGazN6VnhKbmwwcnVU
            L2Rvb21pK1BadzdqOWJJN2RJVW45SzgK8hh25GwYjsvcTENn/oFvLYycyBkzc5v1
            8+BPmy3IxCJqRDaXnBDa0bd0BXjNyXRdVi1fmG9lPG1RgJeTfXvmCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T22:53:38Z"
    mac: ENC[AES256_GCM,data:3la+rBLJUPiW8otjjqUjI51/ZQHMZpBTrBGXcsZNNXWWQHPNIQOUJfMfBNyKjguB9/F43NHL3pCRlMUbxttQv3UiC9XYpap4mXfHAno4T3bf4fm+2/T+thCc0CI4UBDlH7q0VsAWuKsWwrvg9I3ueBuBm5xd3VIx6lervAXpYWs=,iv:NvB8lLZO3j9Pg4gT78ztZpoX8jByqrq7aIhokG4rdZY=,tag:36JOwPEk4NgJUTE5EHrWbw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
