apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:ntwEnwDxMujnH9QA+2/FUCgUc9Af27/TPFxEdbJ+ISQ=,iv:z5rvTlRoHeaAKskApZrWgmZCdwhY7zqqfCO3Moe02N4=,tag:rhXf3V/U1F9eM7lxXVxYiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqYjM1WVVrYmJxcXJYbW1v
            THhwT2FPMXJ4ZDBiU01BNG9saERNQ1lmSkYwCmlhNDg2SlQ5aitqMWtkUjF2L2JT
            aFdZWVhqbFFNenRJdk5DdFJSbi9BOFEKLS0tIENTRCttYnRqVmdCOEpNS1J3VzlN
            RmVkaFdGNEo5dHkxYkh4ei96d2FjanMK3ZyEcXaa5Y27TmVWbZNWDYk89mTWpkwA
            zSdF6dOjHcsNtsoSkHB2DsM6R0IsHWitBmp2BppwMgWyWRLJxYLqHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T22:59:40Z"
    mac: ENC[AES256_GCM,data:69/BSKNrphS+t4bGtBMyj6VPWGIVAryEJFEkE38TMAgnclat2G+j+aVEGJmWSmHyWXG6Hyg92oWyTvhxQ54Zr6WgRJpxCPExlbk3KLvLoW5P4kWFqcHPteT7IkQZxZHg0D+Oo+57mI7Ofch9XbjknO+0/XfkuB9KY9NoqKxJgoM=,iv:EoubltIEdyWru078hgg+T/5vnmokxlB46io9sTdYR7Y=,tag:B1DEPsP7gzQw8NOXWI9Fqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
