apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:rafUFx1TxyWPfWH5nYe6IWOvqMuPyXGEhc/m9DsqjgwBrh+c05AGLQ==,iv:zfLRhmye6J5Ia0psMNqyPmq22PMXCaSojZkngpqG4H4=,tag:7vickuVQHxHqY8qURKiQxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBdGwwMmZjaXNibVBBS3g1
            MjVDbFhlNDhXODl2aW8rZVpNZGZNbDlCQVMwClA4cTM1ZXNZNWFsTmVMWUptRisz
            QTQ3YjlSVXpLSmFGNVd5V2ZrZjNLRFkKLS0tIEF2bWJ5Q2ludTJuTlhDYXlTUkRM
            b1hpbmd0WFpiYWtiVGtaK1dMTkdubmcKD3n8N85k51o4Jo48AUtCym69h3h6op7T
            MBpBltRkEi8BDaIAr47ii1bYNO8jhdOLwhtHV3GGhtRNDgkF99D3Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-03T21:27:46Z"
    mac: ENC[AES256_GCM,data:TF/Kkl1wBH1U/Z3hUUfw9p9TZNBc68GhQrrQE7/Dz8pFAj8H9TDl96kPWUgoZ3uatxrSh7sqqhgyKPpUZdptI00Xs62uAjAw9pBTopJItbEXNtgG8BxtBgGZ36/0H+2GvYwhmplaJNdW7dV+pVGjkjakkw4IwBpM58pp0Ky3anI=,iv:fot7sCLgsIQw8qYS4JYVhfkrhkfE+DEvT2idQ/XPeQY=,tag:K0eSJs73phXtpGFbD4/qTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
