apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:cldIlsgM7jd/Fy4sV4/HU55t7TI1n2phCvfY57JE3VGHvQXBDO/xqw==,iv:zXInnNQkrPlh6jqhNyiLcRV32dPx5+7EwfYpuhAt9D4=,tag:0RLGXw8OtDdbKuEglwvDVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzV0UxY011QUZubjgzUHlp
            cHNpWnMvcm5EN1ZJOVMyRi9PNnh2aFVVRFI4CmE4RS8zbGt1WEVtL2w2SjdhTi85
            VW5maERmV0FkdHVFcE40NmZualZsYWcKLS0tIDQ4Q0RzYmRyZm92UE5RR2J0dExH
            aU42RlRpdklhenMxa0ZKb1ZXVlFKaFkKkxjM4HssIjl4nsniQZiwekyEHxhlChf0
            oy3m5iT6cuksvAEkeCGF1zLXdbNJl98qQQldnWOaZHGFJM3bOaSjeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T22:09:48Z"
    mac: ENC[AES256_GCM,data:Z0AXW29VIMAi5ykGSJ6v21x48Zx3mlFKd/ZDnvaOTJfSxGph9dqJ9oPxBPaerogqGQilY6vktpeuU/QTnvYw60QuVJBvyoQMuTUrWeDp4d2j55ugMEXZ6cBkao+8x9/6lRteqTl6lvZeWO/NUKp2Xwa4XHbtP+FZQL+8/LQt/8E=,iv:DBZXAmxCn/BC4f37RGeP+oW1oFnkaRup9QjNd7iimW0=,tag:BDimSjAf76wWjnwacfspKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
