apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:v5k1u05HO8mfMm+E8pqcl3iKJ/KQicNfQn98Uaj97eMLkYQiyJ7F/A==,iv:u5tg57hCqCWOc95QporDZPQXlUXTTrD1FCviWeuoC/I=,tag:r51gApiLSc5CYlFZMWFwNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RUNPT3hpN0ZGQ0plTEFV
            VU43ayttTzdUcEFPWVBLYXh6cFFWV3pTaWlrCnBCZGhPTzlHR0tuODZBenEwVzBY
            emJ5cVB2TU9NL0dMcEZPSkJ4TVRBSXcKLS0tIEFUZ2FzbHhPbGlBbC9JK3JzQWxR
            eG13Wkx6cTYrZlh2UUEwaDQ3dUVTRlUKNlaypA/yH7XXKlXYs6HcXnxpUBtwR1It
            m6T+yEWh3HBD+zDvyKR9/d4LP0bDbNMzSu+V+tj33njmRS8K/lDGBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T20:04:29Z"
    mac: ENC[AES256_GCM,data:DUj7dZrH19Nma2ZWvTjPa0g4dVzk5TW2YJu4jpoGQ7F4bgkWuMHWKzsX49aljd9XUV54+En04y0VIiKPUF/UPwGCD6KH2JG5HO586fVuDvYc5lVjakjNUSz2p7G63HWiSrZbSGeUDvU3kFsjZk8CA4LhJ4BtKc7orLqkrQhe6lE=,iv:o36DPk0sXDU5uM1+uWaamhFK45hkGTj/E7sH/yg+qTI=,tag:l9atoAC1qi+CkrZ3D503Hg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
