apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:TobGir2Ayk1KDC2B8y+ax2BSOzKpVQx7Wdp9S2TdksQAX4ArgYVm0Q==,iv:/BHYrcfOIpZFzlQlDSihR7eEC67x/ETxCrGEp2gwCcg=,tag:hlkNYyTI3GBEVLfGs28lrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdzRJT1QyaFRiNTdTb3FY
            ckFuaXVlc3FRbTkrMXJNbmlxZ0VwNGpnTVY0CnFvdHB0c0l4eFN5dXdkYkM4Q0tQ
            OWJCNHNNR3ZnUVNaeUN1QlMrK3NTMncKLS0tIFZCVTYycGo2NVpvZVVmQURYS2ZI
            ak9CR3ZmdVdrS3htdWVpVXhYSllBd2cK/L6SUWWTVU14+Pz8FanmmiVqZkA/Xsyl
            ijktMO2gEeBr1wrNEueD57CpIs5PGpSI8D5DGgADRmGWvjXjN8UWCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-04T19:21:20Z"
    mac: ENC[AES256_GCM,data:fVSR1+hnzw9fRmDTZF7Yh/pLz7u/f4OIs4cddLV/d8BZGVYBva2IO/VBIR8+epJOpPx0v2E8zZgf2berG64oRYoKduDUbPLi4inkv42YxUiclhEk72u0XDTvqd1BFjR5juvWOwXPKt4lcwCtMP10HeMqrAFDQ5i8Q9uTLkOFp4M=,iv:+fJDFujZ1ezdpt1o4FQspXvNQpSiJ3I2X5A5fuxuftc=,tag:c61+EJNgDQgXpoSpY9jdzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
