apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:9PLs668SGdNP7iRZNWfy7yoy5ysBPylDyF/bwcEOR8Z/JjldZNJE/w==,iv:3yWrp309f0b3FSsCMnHiBZxe0JwX7OGcYmRVK3A7bQ4=,tag:7JJPcD3rHRUjd/evZTSQXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1n8w03k05vh4zpyw9m3k8rsm7l648tt0sxqchxmadenfpkgv0juqsmzc06z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaEl5TG1DbFI3elJKSmFv
            ck1JN29wRG9nSjRjajlQYnJmcVVhN2UrMTBJCkxUdEtCOCsrSjZxVldQekVjeGJK
            SDlKdUdCaTI2SFVvaHI2T3JrRmVoTG8KLS0tIE51dGlKZmxMdDlBTWduZzl5OE5D
            S1EvZU1GcWRhbUg4KzBlaU05ZlBLMXMKG0p4zu5kYl2trW+TccDG0Rc+0Y9AIZTo
            MaQx72W4twqRSkUbKIBLcpdY3anISvrF3AcxnkfE+VRhzWZ08T9bOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-05T22:53:38Z"
    mac: ENC[AES256_GCM,data:3s6qspqEcSBNpVV3qZRFyg6xGd1pDuD0uwOFnqBWyUHL1X6sWuf92EzezKi32u1oKd0bAykAbnVHZMw3hmTBRLOfRey45IWvBhxJF1MsaXRpa0jBU/GSW4KwuZsuomaf/cXeuPG6a7iCE3vdsr9gYrivQClyNVDv6Qq3NHGrksc=,iv:9EgM33WF7IDkvQbDzgoQR33Nh1//yN39iN2VVZT7jHI=,tag:ZE5IgmEXYJl1LyR7vz8Lrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
